version: "3.3"

services:
    frontend-web:
        stdin_open: true
        tty: true
        build: 
            context: ./frontend-web
            args:
                - HOST=${HOST}
                - PORT_MAIN=${PORT_MAIN}
                - PORT_SPEED=${PORT_SPEED}
        ports:
            - "${PORT_MAIN}:${PORT_MAIN}"
            - "${PORT_SPEED}:${PORT_SPEED}"
        depends_on:
            - www
        volumes:
            - ./nginx/nginx_local.tmp:/nginx.tmp:rw
        command: /bin/bash -c "envsubst '$${PORT_MAIN} $${PORT_SPEED}' < /nginx.tmp > /etc/nginx/conf.d/nginx.conf && exec nginx -g 'daemon off;'";
        
    www:
        stdin_open: true
        tty: true
        build: 
            context: ./www
            args:
                - DB_host=${DB_host}
                - DB_port=${DB_port}
                - DB_user=${DB_user}
                - DB_password=${DB_password}
                - DB_database=${DB_database}
                - DB_database_double=${DB_database_double}
