version: '3.3'

services:
    nginx:
        #restart: always
        image: nginx:latest
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./nginx/nginx_cert.tmp:/etc/nginx/conf.d/nginx.conf:ro
            - ./certbot/www:/var/www/certbot:ro
            - ./certbot/conf:/etc/letsencrypt:ro

    certbot:
        image: certbot/certbot:latest
        volumes:
            - ./certbot/www/:/var/www/certbot/:rw
            - ./certbot/conf/:/etc/letsencrypt/:rw
        depends_on:
            - nginx
        command: certonly --webroot -w /var/www/certbot/ --force-renewal --email ${EMAIL} -d ${DOMAIN} --agree-tos
